add cookies commands
fedora-infra/maubot-fedora pull request #15
Opened 2023-10-12 06:16 UTC by ryanlerch

this adds two new commands for cookies:

* !cookie give -- which does the same thing as name++
* !cookie count -- which gives a count of cookies for a user

2023-10-12 09:11 UTC, abompard requested changes

2023-10-13 03:58 UTC, ryanlerch commented on fedora/cookie.py
> +            "SELECT release, count(release) AS count "
fixed -- also expanded the test on this for better testing and with values other than 1

2023-10-13 03:58 UTC, ryanlerch commented on fedora/cookie.py
> +        self.plugin.log.warn(user)
fixed

2023-10-13 04:30 UTC, abompard commented on fedora/cookie.py
> +        dbq = "SELECT SUM(value) FROM cookies WHERE to_user = $1"
I suggest adding to `db.py`:

```diff
@@ -38,3 +38,12 @@ async def upgrade_v2(conn: Connection) -> None:
         CREATE INDEX idx_cookies_to_user_release ON cookies (to_user, release);
     """
     )
+
+
+@upgrade_table.register(description="Add index on cookie.to_user")
+async def upgrade_v3(conn: Connection) -> None:
+    await conn.execute(
+        """
+        CREATE INDEX idx_cookies_to_user ON cookies (to_user);
+    """
+    )
```

2023-10-13 05:52 UTC, ryanlerch commented on fedora/cookie.py
> +        dbq = "SELECT SUM(value) FROM cookies WHERE to_user = $1"
thanks! added

2023-10-13 05:52 UTC, ryanlerch commented
just waiting on the checks to pass in CI, and then i will merge, and merge into staging

2023-10-13 15:05 UTC, abompard approved these changes

2023-10-13 15:05 UTC, merged